@Restaurant.API_HostAddress = https://localhost:7147

GET {{Restaurant.API_HostAddress}}/api/weatherforecast/Ex
Accept: application/json
ProjectUrl: {{$projectUrl}}
Guid: {{$guid}}
LocalDate: {{$datetime iso8601}}
Random-int: {{$randomInt}}
###

